name: py-dl
channels:
  - conda-forge
dependencies:
  - python=3.6
  - git
  - gym
  - jupyter
  - numpy>=1.18.1
  - h5py
  - scipy
  - toolz
  - bokeh
  - notebook
  - matplotlib
  - pillow
  - pandas
  - pandas-datareader
  - scikit-learn
  - scikit-image
  - snakeviz
  - ujson
  - pip
  - s3fs
  - ipywidgets
  - cachey
  - python-graphviz
  - zarr
  - tensorflow>=2.2 
  - tensorflow-gpu 
  - tensorflow-datasets
  - keras
  - opencv
  - pydot
  - seaborn
